name: jimmyvandewall2
favicon: null
layout_spectrum: 0.40286
typography_spectrum: 0.85353
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Reluctant photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#848484'
    - '#5a5a5a'
    - '#c8c8c8'
    - '#fdfdfd'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
