name: jimmyvandewall2
favicon: null
layout_spectrum: 0.7814932046458125
typography_spectrum: 0.1045749259646982
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5847215810790658
  lightness: 0.4726167251355946
  saturation: 0.3277026398573071
  rhythmicContrast: 0.5205370362382382
purpose: []
