name: jimmyvandewall2
favicon: null
layout_spectrum: 0.01491
typography_spectrum: 0.28346
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#848484'
    - '#5a5a5a'
    - '#c8c8c8'
    - '#fdfdfd'
  brandStrength: 0.375
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
